- name: 'Build Jenkins AMI'
  hosts: localhost
  tasks:
  - set_fact:
       custom_policy:
          Version: '2012-10-17'
          Statement:
          - Sid: Stmt1312295543082
            Action:
            - ec2:DescribeSpotInstanceRequests
            - ec2:CancelSpotInstanceRequests
            - ec2:GetConsoleOutput
            - ec2:RequestSpotInstances
            - ec2:RunInstances
            - ec2:StartInstances
            - ec2:StopInstances
            - ec2:TerminateInstances
            - ec2:CreateTags
            - ec2:DeleteTags
            - ec2:DescribeInstances
            - ec2:DescribeKeyPairs
            - ec2:DescribeRegions
            - ec2:DescribeImages
            - ec2:DescribeAvailabilityZones
            - ec2:DescribeSecurityGroups
            - ec2:DescribeSubnets
            - iam:ListInstanceProfilesForRole
            - iam:PassRole
            - s3:GetObject
            - sts:AssumeRole
            Effect: Allow
            Resource: "*"

  - include_role:
      name: alpha-deploy-lib/deploy-instance
    vars:
      settings:
        VolumePath: /var/lib/jenkins
        ServiceAlias: jenkins
        CustomPolicy: '{{ custom_policy | to_json }}'

